apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app 
    spec:
      containers:
        - name: spring-container
          image: shubham242/spring-image
          ports:
            - containerPort: 8080 
